version: '3.0'

services:
  rasa_core:
    image: rasa/rasa_core:latest
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./models/dialogue:/app/model"
    - "./config:/app/config"
    - "./credentials:/app/credentials"
    command:
    - start
    - -d
    - ./model
    - -c
    - facebook
    - -u
    - current/nlu
    - --endpoints
    - config/endpoints.yml
    - --credentials
    - credentials/credentials.yml

  action_server:
    image: rasa/rasa_core_sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./actions:/app/actions"

  rasa_nlu:
    image: rasa/rasa_nlu:latest-full
    networks: ['rasa-network']
    ports:
    - "5000:5000"
    volumes:
    - "./models/:/app/projects"
    - "./logs:/app/logs"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8080:8080"

networks: {rasa-network: {}}